'use strict';
document.documentElement.classList.add('js');
const configNode=document.getElementById('petica-config');
const config=configNode?JSON.parse(configNode.textContent):{base:'',lang:'fr'};
const say=(fr,ar)=>config.lang==='ar'?ar:fr;
const csrfToken=()=>document.querySelector('meta[name="csrf-token"]')?.content||'';
async function api(path,body){const response=await fetch(config.base+'/api'+path,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrfToken()}:{},body:body?JSON.stringify({...body,lang:config.lang}):undefined});let result;try{result=await response.json();}catch{throw new Error(say('Réponse indisponible. Réessayez.','الاستجابة غير متاحة. حاول مجددًا.'));}if(!response.ok||!result.success)throw new Error(result.error?.message||say('Une erreur est survenue.','حدث خطأ.'));return result.data;}
const toggle=document.querySelector('.menu-toggle');const nav=document.getElementById('main-nav');
toggle?.addEventListener('click',()=>{const open=!nav.classList.contains('open');nav.classList.toggle('open',open);toggle.setAttribute('aria-expanded',String(open));});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&nav?.classList.contains('open')){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.focus();}});
const reduce=window.matchMedia('(prefers-reduced-motion: reduce)');
if('IntersectionObserver'in window&&!reduce.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target);}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(el=>observer.observe(el));}
document.querySelectorAll('form:not(#nero-form)').forEach(form=>{form.addEventListener('submit',()=>{if(!form.checkValidity())return;form.dataset.submitting='true';form.querySelectorAll('button[type=submit],button:not([type])').forEach(button=>{button.disabled=true;});});});
window.addEventListener('pageshow',()=>document.querySelectorAll('form[data-submitting]').forEach(form=>{delete form.dataset.submitting;form.querySelectorAll('button').forEach(button=>button.disabled=false);}));
document.querySelector('.notice.error')?.focus();
document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(button.dataset.copy);button.textContent=say('Copié','تم النسخ');}catch{button.textContent=say('Copiez le lien affiché ci-dessous','انسخ الرابط المعروض أدناه');}}));
// Locally bundled QR generation: only exact, server-authorized URL strings.
const qrNodes=[...document.querySelectorAll('[data-qr]')];
if(qrNodes.length){const script=document.createElement('script');script.src=config.base+'/js/vendor/qrcode.min.js';script.onload=()=>qrNodes.forEach(el=>{new QRCode(el,{text:el.dataset.qr,width:256,height:256,colorDark:'#1e1333',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});});script.onerror=()=>qrNodes.forEach(el=>{el.textContent=say('Génération QR indisponible ; le lien reste accessible.','توليد QR غير متاح؛ الرابط يبقى متاحًا.');});document.head.append(script);}
document.querySelectorAll('[data-export-qr]').forEach(button=>button.addEventListener('click',()=>{const block=button.closest('.qr-block');const canvas=block?.querySelector('canvas');if(!canvas){button.textContent=say('QR indisponible','QR غير متاح');return;}const a=document.createElement('a');const exportCanvas=document.createElement('canvas');exportCanvas.width=320;exportCanvas.height=320;const ctx=exportCanvas.getContext('2d');ctx.fillStyle='#ffffff';ctx.fillRect(0,0,320,320);ctx.drawImage(canvas,32,32);a.href=exportCanvas.toDataURL('image/png');a.download='PETICA-QR.png';a.click();}));
const dialog=document.getElementById('nero-dialog');const launcher=document.querySelector('.nero-launcher');
if(launcher)launcher.hidden=false;launcher?.addEventListener('click',()=>{dialog.showModal();dialog.querySelector('textarea').focus();});
document.querySelector('[data-close-dialog]')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('close',()=>launcher.focus());
document.getElementById('nero-form')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const input=form.querySelector('textarea');const button=form.querySelector('button');const messages=dialog.querySelector('.nero-messages');const question=input.value.trim();if(!question)return;const q=document.createElement('p');q.className='nero-message question';q.textContent=question;messages.append(q);const answer=document.createElement('div');answer.className='nero-message';answer.textContent=say('Je cherche dans les informations PETICA…','أبحث في معلومات PETICA…');messages.append(answer);button.disabled=true;try{const r=await api('/nero/ask',{message:question});answer.textContent=r.answer;if(r.action){const link=document.createElement('a');link.href=config.base+'/'+config.lang+'/'+r.action;link.textContent=say('Ouvrir la page utile','فتح الصفحة المناسبة');answer.append(link);}input.value='';}catch(error){answer.textContent=error.message;}finally{button.disabled=false;messages.scrollTop=messages.scrollHeight;input.focus();}});
let notificationIds=null;
async function refreshSignals(){if(document.visibilityState!=='visible')return;const movement=document.querySelector('[data-movement]');if(movement){try{const data=await api('/movement');movement.textContent=new Intl.NumberFormat(config.lang==='ar'?'en-US':'fr-FR').format(data.remaining);}catch{/* Preserve the last real count. */}}const target=document.querySelector('[data-notifications]');if(target){try{const data=await api('/notifications');const ids=data.items.map(n=>n.id).join(',');if(notificationIds!==null&&ids!==notificationIds&&!target.querySelector('.refresh-notifications')){const a=document.createElement('a');a.className='button secondary refresh-notifications';a.href=location.href;a.textContent=say('De nouvelles notifications sont disponibles · afficher','توجد تنبيهات جديدة · عرض');target.prepend(a);}notificationIds=ids;}catch{/* Existing notifications remain readable. */}}}
if(document.querySelector('[data-notifications],[data-movement]')){refreshSignals();setInterval(refreshSignals,15000);document.addEventListener('visibilitychange',refreshSignals);}
document.querySelectorAll('[data-load-map]').forEach(button=>button.addEventListener('click',async()=>{const host=button.closest('.map-host');const status=host.querySelector('.map-status');button.disabled=true;status.textContent=say('Chargement de la carte…','تحميل الخريطة…');try{await new Promise((resolve,reject)=>{if(window.google?.maps){resolve();return;}const script=document.createElement('script');const cb='peticaMapReady';window[cb]=()=>{delete window[cb];resolve();};script.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(host.dataset.key)+'&libraries=marker&loading=async&callback='+cb+'&language='+config.lang;script.onerror=reject;document.head.append(script);setTimeout(()=>reject(new Error('timeout')),15000);});const position={lat:Number(host.dataset.lat),lng:Number(host.dataset.lng)};host.classList.add('loaded');const map=new google.maps.Map(host.querySelector('.map-canvas'),{center:position,zoom:15,mapId:host.dataset.mapId,gestureHandling:'cooperative'});new google.maps.marker.AdvancedMarkerElement({map,position,title:say('Position partagée par le visiteur','موقع شاركه الزائر')});new google.maps.Circle({map,center:position,radius:Number(host.dataset.accuracy),strokeColor:'#4e2f82',strokeOpacity:.6,fillColor:'#4e2f82',fillOpacity:.12});status.textContent=say('Position du visiteur · précision indiquée par le cercle.','موقع الزائر · الدائرة تشير للدقة.');button.hidden=true;}catch{status.textContent=say('Carte indisponible. Utilisez le lien Google Maps ci-dessus.','الخريطة غير متاحة. استخدم رابط خرائط Google أعلاه.');button.disabled=false;}}));

// Real upload progress; native multipart POST remains the no-JavaScript path.
document.querySelectorAll('form[enctype="multipart/form-data"]').forEach(form=>form.addEventListener('submit',event=>{
 if(!form.checkValidity())return;event.preventDefault();let progress=form.querySelector('progress');if(!progress){progress=document.createElement('progress');progress.max=100;progress.setAttribute('aria-label',say('Progression du téléversement','تقدم الرفع'));form.append(progress);}progress.hidden=false;
 let status=form.querySelector('.upload-status');if(!status){status=document.createElement('p');status.className='upload-status';status.setAttribute('role','status');form.append(status);}status.textContent=say('Téléversement…','جارٍ الرفع…');const xhr=new XMLHttpRequest();xhr.open('POST',form.action);xhr.timeout=120000;
 xhr.upload.onprogress=e=>{if(e.lengthComputable){progress.value=Math.round(e.loaded/e.total*100);status.textContent=progress.value+' %';}};
 xhr.upload.onload=()=>{progress.removeAttribute('value');status.textContent=say('Vérification de l’image…','التحقق من الصورة…');};
 const finish=()=>{form.querySelectorAll('button').forEach(b=>b.disabled=false);delete form.dataset.submitting;progress.hidden=true;};
 xhr.onload=()=>{finish();if(xhr.status>=200&&xhr.status<300){location.assign(xhr.responseURL);return;}const doc=new DOMParser().parseFromString(xhr.responseText,'text/html');status.textContent=doc.querySelector('.notice.error')?.textContent||say('Image non enregistrée. Réessayez.','لم تُحفظ الصورة. حاول مجددًا.');};
 xhr.onerror=xhr.ontimeout=()=>{finish();status.textContent=say('Transfert interrompu. Vos fichiers restent sélectionnés ; vous pouvez réessayer.','انقطع الرفع. الملفات ما زالت محددة ويمكن إعادة المحاولة.');};xhr.send(new FormData(form));
}));
