<?php
function link_page(string $slug,array $params=[]): string {return url(lang().'/'.$slug).($params?'?'.http_build_query($params):'');}
function field(string $key,string $fr,string $ar,$value='',string $type='text',bool $required=false): void {if($type!=='password'&&isset($_POST[$key])&&is_scalar($_POST[$key]))$value=$_POST[$key];echo '<label class="field"><span>'.esc(tr($fr,$ar)).($required?' <span aria-hidden="true">*</span>':'').'</span><input name="'.esc($key).'" type="'.esc($type).'" value="'.esc($value).'"'.($required?' required':'').' '.($type==='password'?'minlength="12" autocomplete="new-password"':'').' '.(in_array($type,['email','tel'],true)?'dir="ltr"':'').'></label>';}
function area(string $key,string $fr,string $ar,$value='',bool $required=false): void {echo '<label class="field"><span>'.esc(tr($fr,$ar)).'</span><textarea name="'.esc($key).'" rows="4"'.($required?' required':'').'>'.esc($value).'</textarea></label>';}
function select_field(string $key,string $fr,string $ar,array $options,$value=''): void {echo '<label class="field"><span>'.esc(tr($fr,$ar)).'</span><select name="'.esc($key).'">';foreach($options as $k=>$v)echo '<option value="'.esc($k).'"'.((string)$value===(string)$k?' selected':'').'>'.esc(is_array($v)?tr(...$v):$v).'</option>';echo '</select></label>';}
function check_field(string $key,string $fr,string $ar,bool $value=false): void {echo '<label class="check"><input type="checkbox" name="'.esc($key).'" value="1"'.($value?' checked':'').'> <span>'.esc(tr($fr,$ar)).'</span></label>';}
function hidden(string $k,$v): void {echo '<input type="hidden" name="'.esc($k).'" value="'.esc($v).'">';}
function form_start(string $action,string $next='',bool $multipart=false): void {global $request_url;echo '<form method="post" action="'.esc($request_url).'"'.($multipart?' enctype="multipart/form-data"':'').' class="form-stack">';hidden('_csrf',csrf());hidden('_action',$action);hidden('lang',lang());if($next!=='')hidden('_next',$next);}
function submit(string $fr='Enregistrer',string $ar='حفظ'): void {echo '<button class="button" type="submit">'.esc(tr($fr,$ar)).'</button>';}
function form_end(string $fr='Enregistrer',string $ar='حفظ'): void {submit($fr,$ar);echo '</form>';}
function scene(int $n,string $alt='',string $class='',bool $critical=false): void {$base=url('assets/scenes/image-'.sprintf('%02d',$n));$small=$n===21?480:960;$dims=$n===21?[500,500]:([1=>[2400,1600],2=>[1008,1792],5=>[2400,1200],6=>[2400,1792],12=>[2400,1600],13=>[2650,1600],14=>[2400,1600]][$n]??[1792,2240]);echo '<picture class="scene '.esc($class).'">';if(in_array($n,[1,13],true))echo '<source media="(max-width: 767px)" srcset="'.esc($base.'-mobile.webp').'">';echo '<img src="'.esc($base.'-'.$small.'.webp').'"'.($n!==21?' srcset="'.esc($base.'-480.webp').' 480w, '.esc($base.'-960.webp').' 960w, '.esc($base.'-1600.webp').' 1600w" sizes="(max-width: 767px) 100vw, 80vw"':'').' width="'.$dims[0].'" height="'.$dims[1].'" alt="'.esc($alt).'" loading="'.($critical?'eager':'lazy').'"'.($critical?' fetchpriority="high"':'').' decoding="async"></picture>';}
function product_image(string $name,string $alt=''): void {echo '<img class="product-photo" src="'.esc(url('assets/images/'.$name)).'" width="800" height="510" alt="'.esc($alt).'" loading="lazy">';}
function empty_state(string $fr='Aucun élément pour le moment.',string $ar='لا توجد عناصر حاليًا.'): void {echo '<div class="empty"><p>'.esc(tr($fr,$ar)).'</p></div>';}
function pagination(array $meta): void {global $request_path;if(($meta['pages']??0)<2)return;echo '<nav class="pagination" aria-label="'.esc(tr('Pagination','الصفحات')).'">';foreach(['previous'=>-1,'next'=>1] as $k=>$offset){$p=$meta['page']+$offset;if($p<1||$p>$meta['pages'])continue;$args=$_GET;$args['page']=$p;echo '<a class="button secondary" href="'.esc($request_path.'?'.http_build_query($args)).'">'.esc($offset<0?tr('Précédent','السابق'):tr('Suivant','التالي')).'</a>';}echo '<span>'.(int)$meta['page'].' / '.(int)$meta['pages'].' · '.(int)$meta['total'].'</span></nav>';}
function detail_list(array $data): void {echo '<dl class="details">';foreach($data as $label=>$v){if(is_array($v))continue;echo '<div><dt>'.esc($label).'</dt><dd>'.esc($v===null||$v===''?tr('Non renseigné','غير محدد'):$v).'</dd></div>';}echo '</dl>';}
function data_table(array $rows,array $columns,?callable $actions=null): void {if(!$rows){empty_state();return;}echo '<div class="table-scroll" role="region" tabindex="0" aria-label="'.esc(tr('Résultats','النتائج')).'"><table><thead><tr>';foreach($columns as $key=>$labels)echo '<th scope="col">'.esc(is_array($labels)?tr(...$labels):$labels).'</th>';if($actions)echo '<th scope="col">'.esc(tr('Actions','إجراءات')).'</th>';echo '</tr></thead><tbody>';foreach($rows as $r){echo '<tr>';foreach($columns as $key=>$labels)echo '<td>'.esc($r[$key]??'—').'</td>';if($actions){echo '<td class="table-actions">';$actions($r);echo '</td>';}echo '</tr>';}echo '</tbody></table></div>';}
function label_status(string $status): string {$map=['present'=>['Présent','موجود'],'lost'=>['Perdu','ضائع'],'deceased'=>['Décédé','متوفى'],'pending'=>['En attente','قيد الانتظار'],'approved'=>['Approuvé','معتمد'],'rejected'=>['Refusé','مرفوض'],'available'=>['Position partagée','تمت مشاركة الموقع'],'denied'=>['Permission refusée','رُفض الإذن'],'not_requested'=>['Position non demandée','لم يُطلب الموقع'],'expired'=>['Position expirée','انتهت مدة حفظ الموقع'],'unavailable'=>['Position indisponible','الموقع غير متاح']];return isset($map[$status])?tr(...$map[$status]):$status;}

function catalogue_price(string $code): string {$p=one('SELECT price_tnd FROM products WHERE code=? AND active=1 AND commercial_approved=1',[$code]);return $p?money((int)round((float)$p['price_tnd']*1000)):tr('Tarif en attente de validation','سعر في انتظار الموافقة');}
