<?php $canonical=PUBLIC_URL.'/'.lang().'/'.$page;$other=lang()==='fr'?'ar':'fr';$params=$_GET;unset($params['lang']);$alternate=url($other.'/'.$page).($params?'?'.http_build_query($params):'');$registration=link_page($user?(in_array($user['role'],['professional','veterinarian'],true)?'espace-pro/clients.html':($user['role']==='admin'?'admin/compagnons.html':'espace-client/ajouter-compagnon.html')):'compte-type.html');$isForm=str_contains($page,'inscription')||str_contains($page,'ajouter-compagnon'); ?>
<!doctype html><html lang="<?=lang()?>" dir="<?=lang()==='ar'?'rtl':'ltr'?>"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?=esc($title)?> · PETICA</title>
<meta name="description" content="<?=esc(tr('Une identité permanente pour votre compagnon : carte, médaille QR et espace partagé.','هوية دائمة لرفيقك: بطاقة وميدالية QR ومساحة خاصة.'))?>">
<?php if(!$private): ?><link rel="canonical" href="<?=esc($canonical)?>"><link rel="alternate" hreflang="fr" href="<?=esc(PUBLIC_URL.'/fr/'.$page)?>"><link rel="alternate" hreflang="ar" href="<?=esc(PUBLIC_URL.'/ar/'.$page)?>"><meta property="og:title" content="<?=esc($title)?>"><meta property="og:description" content="<?=esc(tr('Une identité permanente. Un lien qui reste.','هوية دائمة. ورابط يبقى.'))?>"><meta property="og:image" content="<?=esc(PUBLIC_URL.'/assets/scenes/image-01-960.webp')?>"><?php endif ?>
<meta name="csrf-token" content="<?=esc(csrf())?>"><meta name="app-base" content="<?=esc(APP_BASE)?>"><meta name="theme-color" content="#1E1333"><link rel="icon" href="<?=esc(url('assets/icons/favicon-32.png'))?>">
<link rel="stylesheet" href="<?=esc(url('css/universe.css'))?>"><script src="<?=esc(url('js/universe.js'))?>" defer></script>
<?php if(!$private&&$page==='index.html'): ?><script type="application/ld+json" nonce="<?=esc($nonce)?>"><?=json_encode(['@context'=>'https://schema.org','@type'=>'Organization','name'=>'PETICA','url'=>PUBLIC_URL,'telephone'=>'+21624300864'],JSON_UNESCAPED_SLASHES|JSON_HEX_TAG)?></script><?php endif ?>
</head><body class="<?=$private?'workspace':'public'?> <?=$isForm?'registration':''?>">
<a class="skip" href="#main"><?=esc(tr('Aller au contenu','الانتقال إلى المحتوى'))?></a>
<header class="site-header"><a class="brand" href="<?=esc(link_page('index.html'))?>" aria-label="PETICA"><img src="<?=esc(url('assets/icons/logo-full-purple.svg'))?>" width="142" height="48" alt="PETICA"></a>
<button class="menu-toggle secondary" aria-expanded="false" aria-controls="main-nav"><?=esc(tr('Menu','القائمة'))?></button>
<nav id="main-nav" aria-label="<?=esc(tr('Navigation principale','التنقل الرئيسي'))?>">
<?php foreach(['world.html'=>['World','العالم'],'tarifs.html'=>['Tarifs','الأسعار'],'comment-ca-marche.html'=>['Comment ça marche','كيف تعمل'],'mouvement.html'=>['Mouvement','الحركة']] as $slug=>$label): ?><a href="<?=esc(link_page($slug))?>" <?=$page===$slug?'aria-current="page"':''?>><?=esc(tr(...$label))?></a><?php endforeach ?>
</nav><div class="header-tools"><a class="lang-switch" href="<?=esc($alternate)?>" lang="<?=$other?>" aria-label="<?=esc($other==='ar'?'العربية':'Français')?>"><?=$other==='ar'?'العربية':'FR'?></a><a class="account-link" href="<?=esc(link_page($user?($user['role']==='admin'?'admin/index.html':(in_array($user['role'],['professional','veterinarian'],true)?'espace-pro/index.html':'espace-client/index.html')):'connexion.html'))?>"><?=esc($user?tr('Mon espace','مساحتي'):tr('Connexion','الدخول'))?></a></div></header>
<?php if($private): ?><nav class="workspace-nav" aria-label="<?=esc(tr('Votre espace','مساحتك'))?>"><?php $nav=str_starts_with($page,'admin/')?['admin/index.html'=>['Production','الإنتاج'],'admin/clients.html'=>['Clients','العملاء'],'admin/compagnons.html'=>['Compagnons','الرفقاء'],'admin/commandes.html'=>['Commandes','الطلبات'],'admin/professionnels.html'=>['Professionnels','المهنيون'],'admin/qr-identites.html'=>['QR','QR'],'admin/codes-promo.html'=>['Catalogue & promos','المنتجات والرموز'],'admin/contenu.html'=>['Contenu','المحتوى'],'admin/parametres.html'=>['Règles','القواعد'],'admin/messages.html'=>['Messages','الرسائل'],'admin/health.html'=>['État du système','حالة النظام'],'crm/index.html'=>['CRM','العلاقات']]: (str_starts_with($page,'crm/')?['crm/index.html'=>['À suivre','للمتابعة'],'crm/clients.html'=>['Contacts','جهات الاتصال'],'crm/prospects.html'=>['Prospects','العملاء المحتملون'],'crm/interactions.html'=>['Échanges','التفاعلات'],'crm/suivis.html'=>['Échéances','المواعيد'],'admin/index.html'=>['Administration','الإدارة']]: (str_starts_with($page,'espace-pro/')?['espace-pro/index.html'=>['Rechercher','البحث'],'espace-pro/clients.html'=>['Clients','العملاء'],'espace-pro/commandes.html'=>['Commandes','الطلبات'],'espace-pro/profil.html'=>['Mon profil','ملفي']]:['espace-client/index.html'=>['Mes identités','هويات رفقائي'],'espace-client/commandes.html'=>['Commandes','الطلبات'],'espace-client/notifications.html'=>['Notifications','التنبيهات'],'espace-client/relations.html'=>['Professionnels','المهنيون'],'espace-client/profil.html'=>['Mon profil','ملفي']]));foreach($nav as $slug=>$label): ?><a href="<?=esc(link_page($slug))?>" <?=$page===$slug?'aria-current="page"':''?>><?=esc(tr(...$label))?></a><?php endforeach ?></nav><?php endif ?>
<main id="main" tabindex="-1"><?php if($flash): ?><div class="notice success" role="status"><?=esc($flash)?></div><?php endif ?><?php if($error): ?><div class="notice error" role="alert" tabindex="-1"><?=esc($error)?></div><?php endif ?><?=$content?></main>
<footer class="site-footer"><a class="brand" href="<?=esc(link_page('index.html'))?>"><img src="<?=esc(url('assets/icons/logo-full-white.svg'))?>" alt="PETICA" width="150" height="50" loading="lazy"></a><p><?=esc(tr('Une identité permanente. Un lien qui reste.','هوية دائمة. ورابط يبقى.'))?></p><nav><?php foreach(['a-propos.html'=>['Qui sommes-nous','من نحن'],'faq.html'=>['FAQ','الأسئلة الشائعة'],'blog/index.html'=>['Journal','المجلة'],'contact.html'=>['Contact','تواصل معنا'],'conditions.html'=>['Conditions','الشروط'],'confidentialite.html'=>['Confidentialité','الخصوصية']] as $slug=>$label): ?><a href="<?=esc(link_page($slug))?>"><?=esc(tr(...$label))?></a><?php endforeach ?></nav><div class="footer-bottom"><span>© <?=gmdate('Y')?> PETICA</span><a href="tel:+21624300864" dir="ltr">+216 24 300 864</a><?php if($user): ?><?php form_start('/auth/logout',link_page('index.html'));form_end('Se déconnecter','تسجيل الخروج');?><?php endif ?></div></footer>
<?php if(!$private&&!$isForm&&$page!=='connexion.html'): ?><a class="floating-cta button" href="<?=esc($registration)?>"><?=esc(tr('Inscrire votre compagnon','سجّل رفيقك'))?><span aria-hidden="true">↗</span></a><?php endif ?>
<button hidden class="nero-launcher" aria-haspopup="dialog" aria-controls="nero-dialog" aria-label="<?=esc(tr('Parler à NERO','تحدث مع NERO'))?>"><img src="<?=esc(url('assets/icons/nero.svg'))?>" width="48" height="48" alt=""><span>NERO</span></button>
<dialog id="nero-dialog" class="nero-dialog" aria-labelledby="nero-title"><header><div><p class="eyebrow">PETICA</p><h2 id="nero-title">NERO</h2></div><button type="button" data-close-dialog aria-label="<?=esc(tr('Fermer','إغلاق'))?>">×</button></header><p><?=esc(tr('Des réponses issues des informations PETICA.','إجابات من معلومات PETICA.'))?></p><div class="nero-messages" aria-live="polite"></div><form id="nero-form"><label for="nero-question"><?=esc(tr('Votre question','سؤالك'))?></label><textarea id="nero-question" name="message" rows="2" maxlength="2000" required></textarea><button class="button" type="submit"><?=esc(tr('Demander à NERO','اسأل NERO'))?></button></form><noscript><a href="<?=esc(link_page('faq.html'))?>"><?=esc(tr('Lire les réponses PETICA','اقرأ إجابات PETICA'))?></a></noscript></dialog>
<script type="application/json" id="petica-config" nonce="<?=esc($nonce)?>"><?=json_encode(['lang'=>lang(),'base'=>APP_BASE,'private'=>(bool)$private],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?></script>
</body></html>
