<?php
require_once __DIR__.'/accounts.php';require_once __DIR__.'/operations.php';require_once __DIR__.'/recovery.php';require_once __DIR__.'/nero.php';
function dispatch(string $path,string $method,array $b=[]): array {
 $path='/'.trim($path,'/');$u=actor();if(!in_array($method,['GET','POST','PATCH'],true))fail(405,'method','Méthode non autorisée.');if($method!=='GET')csrf_check($b);
 if($path==='/auth/me'&&$method==='GET')return ['user'=>$u,'csrf'=>csrf(),'profile'=>$u?one('SELECT * FROM '.(in_array($u['role'],['professional','veterinarian'],true)?'professional_profiles':'customer_profiles').' WHERE user_id=?',[$u['id']]):null];
 if($path==='/auth/login'&&$method==='POST')return account_login($b);
 if($path==='/auth/register'&&$method==='POST')return account_register($b);
 if($path==='/auth/register-professional'&&$method==='POST')return account_register($b,true);
 if($path==='/auth/logout'&&$method==='POST'){start();$_SESSION=[];session_regenerate_id(true);return ['logged_out'=>true];}
 if($path==='/auth/forgot-password'&&$method==='POST')return reset_request($b);
 if($path==='/auth/reset-password'&&$method==='POST')return reset_confirm($b);
 if($path==='/products'&&$method==='GET')return ['products'=>q('SELECT id,code,name_fr,name_ar,price_tnd,commercial_approved,price_version FROM products WHERE active=1 ORDER BY id')->fetchAll()];
 if($path==='/movement'&&$method==='GET')return movement();
 if($path==='/nero/ask'&&$method==='POST'){rate('nero',30,60);return nero_ask($b,$u);}
 if($path==='/orders/preview'&&$method==='POST'){rate('quote',40,60);return quote_create($b,$u);}
 if($path==='/qr/scans'&&$method==='POST')return scan_create($b);
 if(preg_match('~^/qr/scans/([a-f0-9]{48})/location$~',$path,$m)&&in_array($method,['POST','PATCH'],true))return scan_location($m[1],$b);
 if($path==='/contact'&&$method==='POST'){rate('contact',5,3600);$email=text_field($b,'email',190,true);if(!filter_var($email,FILTER_VALIDATE_EMAIL))fail(422,'email','Email invalide.');q('INSERT INTO contact_requests(name,email,message,language) VALUES(?,?,?,?)',[text_field($b,'name',150,true),$email,text_field($b,'message',6000,true),lang()]);return ['message'=>tr('Votre demande est enregistrée pour PETICA.','تم تسجيل طلبك لدى PETICA.')];}
 if(!$u)fail(401,'authentication','Connectez-vous pour continuer.','سجّل الدخول للمتابعة.');
 if($path==='/profile'){if($method==='GET')return ['profile'=>one('SELECT * FROM customer_profiles WHERE user_id=?',[$u['id']])];return profile_save($b,$u);}
 if($path==='/registration/draft'){if($method==='GET'){$r=one('SELECT step,payload,updated_at FROM registration_drafts WHERE user_id=? AND updated_at>DATE_SUB(UTC_TIMESTAMP(),INTERVAL 30 DAY)',[$u['id']]);return ['draft'=>$r?array_merge($r,['payload'=>json_decode($r['payload'],true)]):null];}unset($b['password'],$b['national_id'],$b['_csrf']);$step=max(2,min(7,(int)($b['step']??2)));q('INSERT INTO registration_drafts(user_id,step,payload) VALUES(?,?,?) ON DUPLICATE KEY UPDATE step=VALUES(step),payload=VALUES(payload)',[$u['id'],$step,json_encode($b,JSON_UNESCAPED_UNICODE)]);return ['saved'=>true,'step'=>$step];}
 if($path==='/uploads'&&$method==='POST')return upload_media($u);
 if($path==='/companions'){if($method==='POST'){if(in_array($u['role'],['professional','veterinarian'],true))fail(422,'beneficiary','Sélectionnez un client autorisé.');return create_companion($b,$u);}return listing('c.*','FROM companions c JOIN companion_owners co ON co.companion_id=c.id WHERE co.user_id=?',[$u['id']],'c.id DESC');}
 if(preg_match('~^/companions/(\d+)$~',$path,$m)){if($method==='GET')return companion_detail((int)$m[1],$u);return edit_companion((int)$m[1],$b,$u);}
 if(preg_match('~^/companions/(\d+)/status$~',$path,$m)&&$method==='POST')return lost_change((int)$m[1],$b,$u);
 if(preg_match('~^/companions/(\d+)/owners$~',$path,$m)){$id=(int)$m[1];allow_companion($id,$u,'identity',$method!=='GET');if($method==='GET')return ['items'=>q('SELECT id,name,status,confirmed_at FROM companion_owner_invites WHERE companion_id=? ORDER BY id',[$id])->fetchAll()];$name=text_field($b,'name',150,true);q('INSERT INTO companion_owner_invites(companion_id,name,invited_by) VALUES(?,?,?)',[$id,$name,$u['id']]);$inviteId=(int)db()->lastInsertId();audit('owner.invited','companion',$id);return ['invite_id'=>$inviteId];}
 if(preg_match('~^/companions/(\d+)/owners/(\d+)/confirm$~',$path,$m)&&$method==='POST'){$cid=(int)$m[1];allow_companion($cid,$u,'identity',true);$i=one('SELECT * FROM companion_owner_invites WHERE id=? AND companion_id=?',[(int)$m[2],$cid]);if(!$i)fail(404,'invite','Invitation introuvable.');q('UPDATE companion_owner_invites SET status="confirmed",confirmed_at=COALESCE(confirmed_at,UTC_TIMESTAMP()) WHERE id=? AND companion_id=?',[$i['id'],$cid]);audit('owner.confirmed','companion',$cid,['invite_id'=>$i['id']]);return ['confirmed'=>true];}
 if(preg_match('~^/companions/(\d+)/vet$~',$path,$m)){if($method==='POST')return visit_save((int)$m[1],$b,$u,true);$d=companion_detail((int)$m[1],$u);return ['items'=>$d['veterinary_records'],'meta'=>$d['veterinary_meta']];}
 if(preg_match('~^/companions/(\d+)/scan-events$~',$path,$m)&&$method==='GET')return scans_list((int)$m[1],$u);
 if(preg_match('~^/scan-events/([a-f0-9]{48})$~',$path,$m)&&$method==='GET')return scan_detail($m[1],$u);
 if($path==='/notifications'&&$method==='GET')return listing('n.id,n.type,n.title,n.body,n.read_at,n.created_at,n.related_type,n.related_id,e.public_id event_id,e.location_status','FROM notifications n LEFT JOIN qr_scan_events e ON e.id=n.related_id AND n.related_type="scan" WHERE n.user_id=?',[$u['id']],'n.id DESC');
 if(preg_match('~^/notifications/(\d+)/read$~',$path,$m)&&$method==='POST'){if(!one('SELECT id FROM notifications WHERE id=? AND user_id=?',[$m[1],$u['id']]))fail(403,'notification','Accès refusé.');q('UPDATE notifications SET read_at=COALESCE(read_at,UTC_TIMESTAMP()) WHERE id=? AND user_id=?',[$m[1],$u['id']]);return ['read'=>true];}
 if($path==='/relationships'&&$method==='GET')return ['items'=>q('SELECT pc.*,p.business_name,p.profession FROM professional_clients pc JOIN professional_profiles p ON p.user_id=pc.professional_user_id WHERE customer_user_id=? ORDER BY pc.id DESC',[$u['id']])->fetchAll()];
 if(preg_match('~^/relationships/(\d+)$~',$path,$m)&&$method==='POST')return relation_confirm((int)$m[1],$b,$u);
 if($path==='/orders'){if($method==='POST')return order_create($b,$u);return listing('id,order_number,total_tnd,status,production_stage,created_at','FROM orders WHERE user_id=? OR ordered_by=?',[$u['id'],$u['id']]);}
 if(preg_match('~^/orders/(\d+)$~',$path,$m)&&$method==='GET')return order_detail((int)$m[1],$u);
 if(preg_match('~^/orders/(\d+)/status$~',$path,$m)&&$method==='POST')return production_change((int)$m[1],$b,$u);
 if(str_starts_with($path,'/professionals')){
  if($path==='/professionals/me'){roles(['professional','veterinarian']);if($method==='GET')return ['profile'=>one('SELECT * FROM professional_profiles WHERE user_id=?',[$u['id']])];return pro_profile_save($b,$u);}
  if($path==='/professionals'&&$method==='GET'){admin();return listing('p.*,u.email','FROM professional_profiles p JOIN users u ON u.id=p.user_id',[],'p.id DESC');}
  if(preg_match('~^/professionals/(\d+)/verification$~',$path,$m)&&$method==='POST'){admin();$state=enum_field($b,'status',['approved','rejected','pending']);if(!one('SELECT id FROM professional_profiles WHERE id=?',[$m[1]]))fail(404,'professional','Profil introuvable.');q('UPDATE professional_profiles SET verification_status=?,verification_notes=?,verified_by=?,verified_at=UTC_TIMESTAMP() WHERE id=?',[$state,text_field($b,'notes',2000),$u['id'],$m[1]]);audit('professional.'.$state,'professional',(int)$m[1]);return ['verified'=>true];}
  roles(['professional','veterinarian']);pro_approved($u);
  if($path==='/professionals/clients'){if($method==='POST')return pro_relation_request($b,$u);return listing('pc.id,pc.customer_user_id,pc.consent_status,pc.scopes,IF(pc.consent_status="accepted",p.first_name,NULL) first_name,IF(pc.consent_status="accepted",p.last_name,NULL) last_name','FROM professional_clients pc LEFT JOIN customer_profiles p ON p.user_id=pc.customer_user_id WHERE pc.professional_user_id=?',[$u['id']],'pc.id DESC');}
  if(preg_match('~^/professionals/clients/(\d+)(/companions)?$~',$path,$m)){if(!one('SELECT id FROM professional_clients WHERE professional_user_id=? AND customer_user_id=? AND consent_status="accepted"',[$u['id'],$m[1]]))fail(403,'relationship','Accord client requis.');if($method==='POST'&&!empty($m[2]))return create_companion($b,$u,(int)$m[1]);$p=one('SELECT first_name,last_name,phone_primary FROM customer_profiles WHERE user_id=?',[$m[1]]);return ['profile'=>$p,'companions'=>q('SELECT c.id,c.name,c.serial_number,c.species,c.status FROM companions c JOIN companion_owners co ON co.companion_id=c.id WHERE co.user_id=?',[$m[1]])->fetchAll()];}
  if(preg_match('~^/professionals/search-serial/(.+)$~',$path,$m)&&$method==='GET'){$serial=urldecode($m[1]);$c=one('SELECT id FROM companions WHERE serial_number=?',[$serial]);if(!$c)fail(404,'not_found','Aucun dossier autorisé.');return companion_detail((int)$c['id'],$u);}
  if($path==='/professionals/recent-companions'&&$method==='GET')return listing('c.id,c.name,c.serial_number,p.first_name,p.last_name,s.session_date last_visit,s.note reason','FROM session_notes s JOIN companions c ON c.id=s.companion_id JOIN companion_owners co ON co.companion_id=c.id AND co.relationship="primary" JOIN customer_profiles p ON p.user_id=co.user_id JOIN professional_clients pc ON pc.customer_user_id=co.user_id AND pc.professional_user_id=s.professional_user_id AND pc.consent_status="accepted" WHERE s.professional_user_id=? AND NOT EXISTS(SELECT 1 FROM session_notes newer WHERE newer.companion_id=s.companion_id AND newer.professional_user_id=s.professional_user_id AND (newer.session_date>s.session_date OR (newer.session_date=s.session_date AND newer.id>s.id)))',[$u['id']],'s.session_date DESC,s.id DESC');
  if(preg_match('~^/professionals/companions/(\d+)/session-notes$~',$path,$m)){if($method==='POST')return visit_save((int)$m[1],$b,$u);allow_companion((int)$m[1],$u);return listing('*','FROM session_notes WHERE companion_id=? AND professional_user_id=?',[$m[1],$u['id']],'session_date DESC,id DESC');}
 }
 if(str_starts_with($path,'/admin')||str_starts_with($path,'/crm')){
  admin();$search=trim((string)($_GET['search']??''));if(mb_strlen($search)>150)fail(422,'search','Recherche trop longue.');$like='%'.$search.'%';
  if($path==='/admin/overview'&&$method==='GET')return ['customers'=>(int)q('SELECT COUNT(*) FROM users WHERE role="customer" AND is_demo=0')->fetchColumn(),'companions'=>(int)q('SELECT COUNT(*) FROM companions c WHERE NOT EXISTS(SELECT 1 FROM companion_owners co JOIN users u ON u.id=co.user_id WHERE co.companion_id=c.id AND u.is_demo=1)')->fetchColumn(),'orders'=>(int)q('SELECT COUNT(*) FROM orders')->fetchColumn(),'ordered_total_tnd'=>(float)q('SELECT COALESCE(SUM(total_tnd),0) FROM orders WHERE status NOT IN ("cancelled","rejected")')->fetchColumn(),'pending_pro'=>(int)q('SELECT COUNT(*) FROM professional_profiles WHERE verification_status="pending"')->fetchColumn()];
  if(preg_match('~^/admin/users/(\d+)$~',$path,$m)){$target=one('SELECT id,email,role,status FROM users WHERE id=?',[$m[1]]);if(!$target)fail(404,'user','Compte introuvable.');if($method!=='GET'){if($target['role']!=='customer')fail(422,'role','Le profil propriétaire concerne un compte client.');$r=profile_save($b,$target);audit('admin.profile.updated','user',(int)$target['id']);return $r;}return ['user'=>$target,'profile'=>one('SELECT * FROM customer_profiles WHERE user_id=?',[$target['id']])];}
  if($path==='/admin/users'&&$method==='GET')return listing('u.id,u.email,u.role,u.status,p.first_name,p.last_name,p.phone_primary,p.governorate,p.address,p.postal_code','FROM users u LEFT JOIN customer_profiles p ON p.user_id=u.id WHERE u.is_demo=0 AND (u.email LIKE ? OR p.first_name LIKE ? OR p.last_name LIKE ?)',[$like,$like,$like],'u.id DESC');
  if(preg_match('~^/admin/users/(\d+)/status$~',$path,$m)&&$method==='POST'){if((int)$m[1]===(int)$u['id'])fail(422,'self_suspend','Ne suspendez pas votre propre compte.');if(!one('SELECT id FROM users WHERE id=?',[$m[1]]))fail(404,'user','Compte introuvable.');$state=enum_field($b,'status',['active','suspended']);q('UPDATE users SET status=?,auth_version=auth_version+1 WHERE id=?',[$state,$m[1]]);audit('user.'.$state,'user',(int)$m[1]);return ['updated'=>true];}
  if($path==='/admin/companions'&&$method==='GET')return listing('c.id,c.name,c.species,c.serial_number,c.status,c.photo_path,p.first_name,p.last_name','FROM companions c LEFT JOIN companion_owners co ON co.companion_id=c.id AND co.relationship="primary" LEFT JOIN customer_profiles p ON p.user_id=co.user_id WHERE c.serial_number LIKE ? OR c.name LIKE ? OR p.first_name LIKE ? OR p.last_name LIKE ?',[$like,$like,$like,$like],'c.id DESC');
  if($path==='/admin/orders'&&$method==='GET')return listing('o.id,o.order_number,o.total_tnd,o.status,o.production_stage,o.created_at,u.email','FROM orders o JOIN users u ON u.id=o.user_id WHERE o.order_number LIKE ? OR u.email LIKE ?',[$like,$like],'o.id DESC');
  if($path==='/admin/products'&&$method==='GET')return ['items'=>q('SELECT * FROM products ORDER BY id')->fetchAll()];
  if(preg_match('~^/admin/products/(\d+)$~',$path,$m)&&$method!=='GET')return product_save((int)$m[1],$b);
  if($path==='/admin/promo'){if($method==='GET')return listing('*','FROM promo_codes');return promo_save($b);}
  if(preg_match('~^/admin/promo/(\d+)/active$~',$path,$m)&&$method==='POST'){if(!one('SELECT id FROM promo_codes WHERE id=?',[$m[1]]))fail(404,'promo','Code introuvable.');q('UPDATE promo_codes SET active=? WHERE id=?',[checked($b['active']??0),$m[1]]);audit('promo.active','promo',(int)$m[1]);return ['updated'=>true];}
  if($path==='/admin/settings'){if($method==='GET')return ['commercial'=>setting('commercial',[])];$old=setting('commercial',[]);$cap=$b['multi_cap']??null;if($cap!==null&&$cap!==''&&(!is_numeric($cap)||(int)$cap<0||(int)$cap>100))fail(422,'cap','Plafond invalide.');$r=['version'=>(int)($old['version']??0)+1,'delivery_millimes'=>8000,'multi_step'=>2,'multi_cap'=>$cap===''||$cap===null?null:(int)$cap,'stacking_approved'=>(bool)checked($b['stacking_approved']??0),'pro_percent'=>10,'secondary_percent'=>10];set_setting('commercial',$r);audit('commercial.updated','settings',null,['before'=>$old,'after'=>$r]);return ['commercial'=>$r];}
  if($path==='/admin/content'){if($method==='GET')return listing('*','FROM content_versions');return content_save($b,$u);}
  if(preg_match('~^/admin/content/(\d+)/restore$~',$path,$m)&&$method==='POST'){$r=one('SELECT * FROM content_versions WHERE id=?',[$m[1]]);if(!$r)fail(404,'content','Version introuvable.');$r['status']='published';return content_save($r,$u);}
  if($path==='/admin/contact-requests'&&$method==='GET')return listing('*','FROM contact_requests');
  if($path==='/admin/health'&&$method==='GET')return ['php'=>PHP_VERSION,'database_connected'=>true,'schema'=>q('SELECT version,applied_at FROM schema_migrations')->fetchAll(),'storage_writable'=>is_writable(UPLOAD_DIR),'location_configured'=>strlen((string)base64_decode((string)cfg('APP_KEY',''),true))===32,'maps_configured'=>(bool)cfg('MAPS_KEY',''),'email_enabled'=>(bool)cfg('EMAIL_ENABLED',false)];
  if(in_array($path,['/crm/contacts','/crm/customers','/crm/leads'],true)){if($method!=='GET')return crm_contact_save($b,$u);$where=$path==='/crm/leads'?' AND kind="prospect"':'';return listing('*','FROM crm_contacts WHERE (name LIKE ? OR email LIKE ? OR phone LIKE ?)'.$where,[$like,$like,$like]);}
  if(preg_match('~^/crm/(?:contacts|customers)/(\d+)$~',$path,$m)&&$method==='GET'){$r=one('SELECT * FROM crm_contacts WHERE id=?',[$m[1]]);if(!$r)fail(404,'contact','Contact introuvable.');return ['contact'=>$r,'activity'=>q('SELECT a.*,u.email actor FROM crm_activity a JOIN users u ON u.id=a.actor_id WHERE contact_id=? ORDER BY a.created_at DESC,a.id DESC LIMIT 100',[$m[1]])->fetchAll(),'orders'=>$r['user_id']?q('SELECT id,order_number,total_tnd,status FROM orders WHERE user_id=? ORDER BY id DESC LIMIT 50',[$r['user_id']])->fetchAll():[]];}
  if(preg_match('~^/crm/contacts/(\d+)/convert$~',$path,$m)&&$method==='POST'){if(!one('SELECT id FROM crm_contacts WHERE id=?',[$m[1]]))fail(404,'contact','Contact introuvable.');$uid=(int)($b['user_id']??0);if(!one('SELECT id FROM users WHERE id=? AND role="customer"',[$uid]))fail(422,'user','Sélectionnez un compte client existant.');q('UPDATE crm_contacts SET user_id=?,kind="customer" WHERE id=?',[$uid,$m[1]]);audit('crm.converted','crm_contact',(int)$m[1]);return ['converted'=>true];}
  if(preg_match('~^/crm/(?:contacts|customers)/(\d+)/(activity|notes|interactions|followups)$~',$path,$m)){if($method==='GET')return listing('*','FROM crm_activity WHERE contact_id=?',[$m[1]]);if($m[2]!=='activity')$b['type']=['notes'=>'note','interactions'=>'interaction','followups'=>'followup'][$m[2]];return crm_activity_save((int)$m[1],$b,$u);}
  if(in_array($path,['/crm/followups','/crm/interactions'],true)&&$method==='GET')return listing('a.*,c.name contact_name','FROM crm_activity a JOIN crm_contacts c ON c.id=a.contact_id WHERE a.type=?',[$path==='/crm/followups'?'followup':'interaction'],'a.due_at IS NULL,a.due_at,a.id DESC');
  if(preg_match('~^/crm/followups/(\d+)/status$~',$path,$m)&&$method==='POST'){$state=enum_field($b,'status',['open','completed']);q('UPDATE crm_activity SET status=?,completed_at=IF(?="completed",UTC_TIMESTAMP(),NULL) WHERE id=? AND type="followup"',[$state,$state,$m[1]]);audit('crm.followup.'.$state,'crm_activity',(int)$m[1]);return ['updated'=>true];}
  if(preg_match('~^/crm/customers/(\d+)/status$~',$path,$m)&&$method==='POST'){$status=enum_field($b,'status',['active','inactive','at_risk']);q('UPDATE crm_contacts SET status=? WHERE id=?',[$status,$m[1]]);audit('crm.status','crm_contact',(int)$m[1]);return ['updated'=>true];}
  if($path==='/crm/segments'&&$method==='GET')return ['items'=>q('SELECT kind,status,COUNT(*) count FROM crm_contacts GROUP BY kind,status')->fetchAll()];
 }
 fail(404,'route','Route ou action introuvable.','المسار أو العملية غير موجودة.');
}
