<?php
require_once __DIR__.'/identity.php';
function round_percent(int $base,int $percent): int {return intdiv($base*$percent+50,100);}
function allocate_discount(array $bases,int $amount): array {$sum=array_sum($bases);$out=array_fill(0,count($bases),0);if(!$sum||!$amount)return $out;$remainders=[];foreach($bases as $i=>$b){$out[$i]=intdiv($b*$amount,$sum);$remainders[$i]=($b*$amount)%$sum;}$left=$amount-array_sum($out);uksort($remainders,fn($a,$b)=>$remainders[$b]<=>$remainders[$a]?:$a<=>$b);foreach(array_keys($remainders) as $i){if($left--<=0)break;$out[$i]++;}return $out;}
function calculate_quote(array $b,?array $u,bool $lock=false): array {
 $rules=setting('commercial',[]);$input=$b['items']??[];if(!is_array($input)||count($input)<1||count($input)>20)fail(422,'cart','Choisissez entre 1 et 20 lignes.','اختر من سطر إلى 20 سطرًا.');
 $rows=[];$ids=[];$secondary=false;$pro=checked($b['professional_discount']??0);if($pro){if(!$u)fail(401,'auth','Connectez-vous.');pro_approved($u);}
 foreach(array_values($input) as $i=>$line){if(!is_array($line))fail(422,'cart','Ligne invalide.');if(isset($line['quantity'])&&(int)$line['quantity']!==1)fail(422,'quantity','Une ligne représente un produit pour un compagnon.');$code=text_field($line,'product_code',30,true);$p=one('SELECT * FROM products WHERE code=? AND active=1'.($lock?' FOR UPDATE':''),[$code]);if(!$p||!$p['commercial_approved'])fail(422,'commercial_unapproved','Tarif en attente de validation PETICA. Choisissez un produit disponible.','السعر في انتظار موافقة PETICA. اختر منتجًا متاحًا.');$cid=(int)($line['companion_id']??0);$invite=(int)($line['owner_invite_id']??0);if($cid&&$u)allow_companion($cid,$u);if($invite){if(!$u||!$cid)fail(403,'secondary','Sélectionnez un compagnon.');allow_companion($cid,$u,'identity',true);if($code!=='id_card'||!one('SELECT id FROM companion_owner_invites WHERE id=? AND companion_id=? AND status="confirmed"',[$invite,$cid]))fail(422,'secondary','Le titulaire confirmé peut recevoir une carte seule.','يمكن للمالك الثانوي المؤكد الحصول على بطاقة فقط.');$secondary=true;}
  $base=(int)round((float)$p['price_tnd']*1000);$discount=$invite?round_percent($base,10):0;$rows[]=['line_id'=>$i,'product_id'=>(int)$p['id'],'product_code'=>$code,'name_fr'=>$p['name_fr'],'name_ar'=>$p['name_ar'],'price_version'=>(int)$p['price_version'],'companion_id'=>$cid?:null,'owner_invite_id'=>$invite?:null,'base'=>$base,'discount'=>$discount,'net'=>$base-$discount];if(!$invite)$ids[$cid?:'new-'.$i]=true;
 }
 $multi=max(0,count($ids)-1)*2;$cap=$rules['multi_cap']??null;if($cap!==null)$multi=min($multi,(int)$cap);$active=(int)($multi>0)+(int)$pro+(int)$secondary;
 if($active>1&&empty($rules['stacking_approved']))fail(422,'stacking_unapproved','Le cumul des remises doit être validé par PETICA.','يجب الموافقة على جمع التخفيضات.');
 $global=$pro?10:$multi;if($global>0){$bases=array_column($rows,'net');$d=allocate_discount($bases,round_percent(array_sum($bases),$global));foreach($rows as $i=>&$r){$r['discount']+=$d[$i];$r['net']-=$d[$i];}unset($r);}
 $promo=null;$code=strtoupper(text_field($b,'promo_code',50)??'');if($code!==''){$promo=one('SELECT * FROM promo_codes WHERE code=?'.($lock?' FOR UPDATE':''),[$code]);if(!$promo||!$promo['active']||($promo['starts_at']&&strtotime($promo['starts_at'].' UTC')>time())||($promo['expires_at']&&strtotime($promo['expires_at'].' UTC')<time())||($promo['usage_limit']!==null&&(int)$promo['used_count']>=(int)$promo['usage_limit']))fail(422,'promo','Code expiré ou indisponible.','الرمز منتهي الصلاحية أو غير متاح.');if($active&&!$promo['stackable'])fail(422,'promo_stacking','Ce code ne se cumule pas aux autres remises.');if($u&&(int)q('SELECT COUNT(*) FROM promo_code_redemptions WHERE promo_code_id=? AND user_id=?',[$promo['id'],$u['id']])->fetchColumn()>=(int)$promo['per_user_limit'])fail(422,'promo_quota','Quota personnel atteint.');$bases=array_map(fn($r)=>!$promo['applicable_product_id']||(int)$promo['applicable_product_id']===$r['product_id']?$r['net']:0,$rows);$eligible=array_sum($bases);if(!$eligible||array_sum(array_column($rows,'net'))<(int)round((float)$promo['min_order_tnd']*1000))fail(422,'promo_eligibility','Panier non éligible.');$amount=$promo['discount_type']==='percent'?round_percent($eligible,(int)$promo['discount_value']):(int)round((float)$promo['discount_value']*1000);$d=allocate_discount($bases,min($eligible,$amount));foreach($rows as $i=>&$r){$r['discount']+=$d[$i];$r['net']-=$d[$i];}unset($r);}
 $delivery=(int)($rules['delivery_millimes']??8000);$sub=array_sum(array_column($rows,'base'));$discount=array_sum(array_column($rows,'discount'));return ['items'=>$rows,'subtotal_millimes'=>$sub,'discount_millimes'=>$discount,'delivery_millimes'=>$delivery,'total_millimes'=>$sub-$discount+$delivery,'currency'=>'TND','pricing_version'=>(int)($rules['version']??1),'promo_id'=>$promo['id']??null,'multi_percent'=>$multi,'input'=>['items'=>$input,'promo_code'=>$code,'professional_discount'=>$pro]];
}
function quote_create(array $b,?array $u): array {$quote=calculate_quote($b,$u);$id=bin2hex(random_bytes(24));q('INSERT INTO quotes(id,user_id,request_hash,payload,expires_at) VALUES(?,?,?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 15 MINUTE))',[$id,$u['id']??null,hash('sha256',json_encode($quote['input'])),json_encode($quote)]);return ['quote_id'=>$id,'quote'=>$quote,'expires_in'=>900];}
function order_create(array $b,array $u): array {return once($u,'order:create',$b,function()use($b,$u){$stored=one('SELECT * FROM quotes WHERE id=? FOR UPDATE',[(string)($b['quote_id']??'')]);if(!$stored||($stored['user_id']!==null&&(int)$stored['user_id']!==(int)$u['id'])||strtotime($stored['expires_at'].' UTC')<time())fail(409,'quote_expired','Recalculez votre devis avant de confirmer.','أعد حساب السعر قبل التأكيد.');$existing=one('SELECT id,order_number,total_tnd FROM orders WHERE quote_id=?',[$stored['id']]);if($existing)return ['order_id'=>(int)$existing['id'],'order_number'=>$existing['order_number'],'total_millimes'=>(int)round((float)$existing['total_tnd']*1000)];$old=json_decode($stored['payload'],true);$quote=calculate_quote($old['input'],$u,true);if(json_encode($quote)!==json_encode($old))fail(409,'price_changed','Le devis a changé. Vérifiez le nouveau total.');$owner=null;$snap=[];foreach($quote['items'] as $line){$cid=(int)$line['companion_id'];if(!$cid)fail(422,'companion','Créez l’identité avant de commander.');$c=allow_companion($cid,$u);$o=primary_owner($cid);if(!$o)fail(422,'owner','Propriétaire principal manquant.');if($owner!==null&&$owner!==(int)$o['user_id'])fail(422,'owners','Une commande doit avoir un seul destinataire propriétaire.');$owner=(int)$o['user_id'];if($u['role']==='customer'&&$owner!==(int)$u['id'])fail(403,'owner','Commande non autorisée.');$secondary=$line['owner_invite_id']?one('SELECT name,confirmed_at FROM companion_owner_invites WHERE id=?',[$line['owner_invite_id']]):null;$snap[]=['secondary_owner'=>$secondary,'companion'=>$c,'owner'=>$o,'qr'=>qr_urls($c),'item'=>$line];}
 $address=text_field($b,'shipping_address',2000,true);$number='P'.gmdate('ymd').strtoupper(bin2hex(random_bytes(5)));q('INSERT INTO orders(order_number,user_id,ordered_by,companion_id,subtotal_tnd,discount_tnd,delivery_fee_tnd,total_tnd,promo_code_id,shipping_address,quote_snapshot) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[$number,$owner,$u['id'],$quote['items'][0]['companion_id'],$quote['subtotal_millimes']/1000,$quote['discount_millimes']/1000,$quote['delivery_millimes']/1000,$quote['total_millimes']/1000,$quote['promo_id'],$address,json_encode(['quote'=>$quote,'production'=>$snap,'shipping_address'=>$address],JSON_UNESCAPED_UNICODE)]);$id=(int)db()->lastInsertId();q('UPDATE orders SET quote_id=? WHERE id=?',[$stored['id'],$id]);foreach($quote['items'] as $l)q('INSERT INTO order_items(order_id,product_id,quantity,unit_price_tnd,line_total_tnd,companion_id,owner_invite_id,net_millimes,discount_millimes) VALUES(?,?,1,?,?,?,?,?,?)',[$id,$l['product_id'],$l['base']/1000,$l['net']/1000,$l['companion_id'],$l['owner_invite_id'],$l['net'],$l['discount']]);if($quote['promo_id']){q('UPDATE promo_codes SET used_count=used_count+1 WHERE id=?',[$quote['promo_id']]);q('INSERT INTO promo_code_redemptions(promo_code_id,user_id,order_id) VALUES(?,?,?)',[$quote['promo_id'],$u['id'],$id]);}q('INSERT INTO order_status_history(order_id,status,changed_by) VALUES(?,"pending",?)',[$id,$u['id']]);audit('order.created','order',$id);return ['order_id'=>$id,'order_number'=>$number,'total_millimes'=>$quote['total_millimes']];});}
function order_detail(int $id,array $u): array {$o=one('SELECT * FROM orders WHERE id=?',[$id]);if(!$o)fail(404,'order','Commande introuvable.');if($u['role']!=='admin'&&(int)$o['user_id']!==(int)$u['id']&&(int)$o['ordered_by']!==(int)$u['id'])fail(403,'order','Accès refusé.');$o['snapshot']=json_decode($o['production_snapshot']??$o['quote_snapshot']??'null',true);unset($o['production_snapshot'],$o['quote_snapshot']);if(in_array($u['role'],['professional','veterinarian'],true)){unset($o['snapshot']);}$items=q('SELECT oi.*,p.name_fr,p.name_ar FROM order_items oi JOIN products p ON p.id=oi.product_id WHERE order_id=? ORDER BY oi.id',[$id])->fetchAll();$frozen=json_decode(one('SELECT quote_snapshot FROM orders WHERE id=?',[$id])['quote_snapshot']??'null',true);foreach($items as $index=>&$item)foreach(['name_fr','name_ar'] as $field)if(isset($frozen['quote']['items'][$index][$field]))$item[$field]=$frozen['quote']['items'][$index][$field];unset($item);return ['order'=>$o,'items'=>$items,'history'=>q('SELECT status,note,created_at,changed_by FROM order_status_history WHERE order_id=? ORDER BY id',[$id])->fetchAll()];}
function production_change(int $id,array $b,array $u): array {if($u['role']!=='admin')fail(403,'admin','Accès refusé.');$stages=['draft'=>'review','review'=>'bat','bat'=>'approved','approved'=>'production','production'=>'ready','ready'=>'shipped','shipped'=>'completed'];return tx(function()use($id,$b,$u,$stages){$o=one('SELECT * FROM orders WHERE id=? FOR UPDATE',[$id]);if(!$o)fail(404,'order','Commande introuvable.');if((int)$o['version']!==(int)($b['version']??0))fail(409,'version','La commande a changé.');$next=(string)($b['stage']??'');if(($stages[$o['production_stage']]??null)!==$next)fail(422,'transition','Transition de production interdite.');$snapshot=$o['production_snapshot'];if($next==='approved'){if(!checked($b['bat_checked']??0))fail(422,'bat','Vérifiez le BAT et les deux QR avant approbation.');$data=json_decode($o['quote_snapshot']??'',true);if(!$data)fail(422,'legacy_snapshot','Commande historique : préparation manuelle documentée requise.');foreach($data['production'] as $p)if(empty($p['companion']['photo_path'])||empty($p['owner']['phone_primary'])||empty($p['owner']['address']))fail(422,'production_data','Photo ou coordonnées manquantes dans le snapshot. Revoir la commande.');$snapshot=$o['quote_snapshot'];}
 $states=['review'=>'contact_required','bat'=>'confirmed','approved'=>'approved','production'=>'in_production','ready'=>'ready','shipped'=>'shipped','completed'=>'completed'];q('UPDATE orders SET production_stage=?,status=?,production_snapshot=?,version=version+1 WHERE id=?',[$next,$states[$next],$snapshot,$id]);q('INSERT INTO order_status_history(order_id,status,note,changed_by) VALUES(?,?,?,?)',[$id,$states[$next],text_field($b,'note',2000),$u['id']]);audit('production.'.$next,'order',$id);return order_detail($id,$u);});}
