<?php
require_once __DIR__.'/core.php';
require_once __DIR__.'/../includes/serial.php';
require_once __DIR__.'/../includes/qr.php';
function companion(int $id): array {$c=one('SELECT * FROM companions WHERE id=?',[$id]);if(!$c)fail(404,'not_found','Compagnon introuvable.','لم يتم العثور على الرفيق.');return $c;}
function primary_owner(int $id): ?array {return one('SELECT u.id,u.email,u.language,p.* FROM companion_owners co JOIN users u ON u.id=co.user_id LEFT JOIN customer_profiles p ON p.user_id=u.id WHERE co.companion_id=? AND co.relationship="primary" ORDER BY co.id LIMIT 1',[$id]);}
function pro_approved(array $u): array {$p=one('SELECT * FROM professional_profiles WHERE user_id=?',[$u['id']]);if(!$p||$p['verification_status']!=='approved')fail(403,'verification_required','Votre compte professionnel doit être approuvé.','يجب الموافقة على حسابك المهني.');return $p;}
function allow_companion(int $id,array $u,string $scope='identity',bool $write=false): array {
 $c=companion($id);if($u['role']==='admin'&&$scope!=='recovery')return $c;
 $own=one('SELECT relationship FROM companion_owners WHERE companion_id=? AND user_id=?',[$id,$u['id']]);
 if($own&&(!$write&&$scope!=='recovery'||$own['relationship']==='primary'))return $c;
 if(in_array($u['role'],['professional','veterinarian'],true)&&!$write&&$scope!=='recovery'){$p=pro_approved($u);$link=one('SELECT pc.* FROM professional_clients pc JOIN companion_owners co ON co.user_id=pc.customer_user_id WHERE pc.professional_user_id=? AND co.companion_id=? AND co.relationship="primary" AND pc.consent_status="accepted"',[$u['id'],$id]);if($link&&in_array($scope,explode(',',$link['scopes']??''),true)&&($scope!=='medical'||$p['profession']==='veterinarian'))return $c;}
 fail(403,'forbidden','Vous ne disposez pas des droits sur ce dossier.','ليس لديك إذن لهذا الملف.');
}
function companion_detail(int $id,array $u): array {
 $c=allow_companion($id,$u);$professional=in_array($u['role'],['professional','veterinarian'],true);
 if($professional){$p=pro_approved($u);$link=one('SELECT pc.scopes FROM professional_clients pc JOIN companion_owners co ON co.user_id=pc.customer_user_id WHERE pc.professional_user_id=? AND co.companion_id=? AND co.relationship="primary"',[$u['id'],$id]);if($p['profession']!=='veterinarian'||!in_array('medical',explode(',',$link['scopes']??''),true))foreach(['medical_info','microchip_number','vaccinated'] as $k)unset($c[$k]);}
 $records=[];$vetMeta=null;try{allow_companion($id,$u,'medical');$history=listing('id,clinic_name,visit_date,reason,diagnosis,treatment,vaccination,notes,created_by','FROM veterinary_records WHERE companion_id=?',[$id],'visit_date DESC,id DESC');$records=$history['items'];$vetMeta=$history['meta'];}catch(ApiError $e){if($e->status!==403)throw $e;}
 $notes=listing('*','FROM session_notes WHERE companion_id=? AND professional_user_id=?',[$id,$u['id']],'session_date DESC,id DESC');
 return ['companion'=>$c,'qr'=>qr_urls($c),'owners'=>$professional?[]:q('SELECT id,name,status,confirmed_at FROM companion_owner_invites WHERE companion_id=? ORDER BY id',[$id])->fetchAll(),'veterinary_records'=>$records,'veterinary_meta'=>$vetMeta,'session_notes'=>$notes['items'],'session_meta'=>$notes['meta']];
}
function validate_companion(array $b,array $u,bool $new=true): array {
 $out=[];$out['name']=text_field($b,'name',100,true);
 if($new)$out['species']=enum_field($b,'species',['dog','cat','horse']);
 foreach(['breed'=>100,'colors_marks'=>255,'microchip_number'=>50,'medical_info'=>6000,'public_contact_name'=>150,'public_contact_phone'=>30] as $k=>$max)$out[$k]=text_field($b,$k,$max);
 $out['sex']=enum_field($b,'sex',['male','female']);$out['date_of_birth']=text_field($b,'date_of_birth',10);
 if($out['date_of_birth']){$d=DateTimeImmutable::createFromFormat('!Y-m-d',$out['date_of_birth']);if(!$d||$d->format('Y-m-d')!==$out['date_of_birth']||$out['date_of_birth']>gmdate('Y-m-d'))fail(422,'date','Date de naissance invalide.','تاريخ الميلاد غير صالح.');}
 $w=$b['weight_kg']??null;$out['weight_kg']=($w===null||$w==='')?null:$w;if($out['weight_kg']!==null&&(!is_numeric($w)||(float)$w<=0||(float)$w>9999))fail(422,'weight','Poids invalide.','الوزن غير صالح.');
 $out['vaccinated']=($b['vaccinated']??'')===''?null:checked($b['vaccinated']);$out['public_show_breed']=checked($b['public_show_breed']??0);$out['public_contact_consent']=checked($b['public_contact_consent']??0);
 if(!$out['public_contact_consent']){$out['public_contact_name']=null;$out['public_contact_phone']=null;}
 if($out['public_contact_phone']&&!preg_match('/^\+?[0-9 ()-]{6,30}$/',$out['public_contact_phone']))fail(422,'phone','Téléphone invalide.');
 foreach(['photo_path','paw_photo_path'] as $k){$path=text_field($b,$k,255);if($path&&!one('SELECT id FROM uploaded_media WHERE user_id=? AND path=? AND private=0',[$u['id'],$path])){if(!$new&&isset($b['id'])&&one('SELECT id FROM companions WHERE id=? AND '.$k.'=?',[(int)$b['id'],$path])){}else fail(422,'media','Photo non autorisée.','الصورة غير مسموحة.');}$out[$k]=$path;}
 return $out;
}
function create_companion(array $b,array $u,?int $beneficiary=null): array {
 $owner=$beneficiary??(int)$u['id'];if(in_array($u['role'],['professional','veterinarian'],true)&&(!empty($b['medical_info'])||!empty($b['microchip_number'])||isset($b['vaccinated'])&&$b['vaccinated']!==''&&$b['vaccinated']!==null)){$pro=pro_approved($u);$relation=one('SELECT scopes FROM professional_clients WHERE professional_user_id=? AND customer_user_id=? AND consent_status="accepted"',[$u['id'],$owner]);if($pro['profession']!=='veterinarian'||!in_array('medical',explode(',',$relation['scopes']??''),true))fail(403,'medical','Droits vétérinaires et accord médical requis.');}if($owner!==(int)$u['id']&&$u['role']!=='admin'){pro_approved($u);if(!one('SELECT id FROM professional_clients WHERE professional_user_id=? AND customer_user_id=? AND consent_status="accepted"',[$u['id'],$owner]))fail(403,'consent','Relation client non autorisée.');}
 if(!one('SELECT user_id FROM customer_profiles WHERE user_id=?',[$owner]))fail(422,'profile','Complétez le profil propriétaire.','أكمل بيانات المالك.');
 return once($u,'companion:create',$b,function()use($b,$u,$owner){$v=validate_companion($b,$u);if(!$v['species'])fail(422,'species','Choisissez une espèce.');$serial=next_serial(db(),$v['species']);if(!preg_match('/^(DOG|CAT|HRS)-[0-9]{9}$/',$serial))fail(409,'serial_limit','Allocation de série indisponible.');$v['serial_number']=$serial;$v['species_code']=substr($serial,0,3);$keys=array_keys($v);q('INSERT INTO companions(`'.implode('`,`',$keys).'`) VALUES('.implode(',',array_fill(0,count($keys),'?')).')',array_values($v));$id=(int)db()->lastInsertId();q('INSERT INTO companion_owners(companion_id,user_id,relationship) VALUES(?,?,"primary")',[$id,$owner]);qr_issue_for_companion(db(),$id);$demo=(int)q('SELECT is_demo FROM users WHERE id=?',[$owner])->fetchColumn();q('INSERT INTO registration_events(companion_id,source,counted) VALUES(?,?,?)',[$id,$demo?'demo':'new',$demo?0:1]);notify($owner,'companion_registered','Identité créée','هوية جديدة · '.$serial,'companion',$id);audit('companion.created','companion',$id);return companion_detail($id,$u);});
}
function edit_companion(int $id,array $b,array $u): array {allow_companion($id,$u,'identity',true);$b['id']=$id;if(in_array($b['replace_photo_field']??'', ['photo_path','paw_photo_path'],true))$b[$b['replace_photo_field']]=$b['replacement_path']??null;$v=validate_companion($b,$u,false);return tx(function()use($id,$b,$v){$args=array_values($v);$args[]=$id;$args[]=(int)($b['version']??0);$sets=implode(',',array_map(fn($k)=>'`'.$k.'`=?',array_keys($v)));$s=q('UPDATE companions SET '.$sets.',version=version+1 WHERE id=? AND version=?',$args);if(!$s->rowCount())fail(409,'version','Le dossier a changé. Rechargez-le avant de modifier.','تغير الملف. أعد تحميله قبل التعديل.');audit('companion.updated','companion',$id);return ['companion'=>companion($id)];});}
function profile_save(array $b,array $u): array {$v=[];foreach(['first_name'=>100,'last_name'=>100,'national_id'=>50,'phone_primary'=>30,'phone_secondary'=>30,'governorate'=>100,'address'=>2000,'postal_code'=>20] as $k=>$len)$v[$k]=text_field($b,$k,$len,in_array($k,['first_name','last_name','phone_primary','governorate','address'],true));if(!preg_match('/^\+?[0-9 ()-]{6,30}$/',$v['phone_primary']))fail(422,'phone','Téléphone invalide.');$keys=array_keys($v);q('INSERT INTO customer_profiles(user_id,`'.implode('`,`',$keys).'`) VALUES('.implode(',',array_fill(0,count($keys)+1,'?')).') ON DUPLICATE KEY UPDATE '.implode(',',array_map(fn($k)=>'`'.$k.'`=VALUES(`'.$k.'`)',$keys)),array_merge([$u['id']],array_values($v)));q('INSERT INTO crm_contacts(user_id,name,email,phone,kind) VALUES(?,?,?,?,"customer") ON DUPLICATE KEY UPDATE name=VALUES(name),email=VALUES(email),phone=VALUES(phone)',[$u['id'],$v['first_name'].' '.$v['last_name'],$u['email'],$v['phone_primary']]);return ['profile'=>one('SELECT * FROM customer_profiles WHERE user_id=?',[$u['id']])];}
function upload_media(array $u): array {
 $f=$_FILES['file']??null;if(!$f||$f['error']!==UPLOAD_ERR_OK||!is_uploaded_file($f['tmp_name']))fail(422,'upload','Téléversement interrompu ou absent.','فشل رفع الملف.');
 if($f['size']>10*1024*1024)fail(413,'upload_size','Image limitée à 10 Mo.');if((int)q('SELECT COUNT(*) FROM uploaded_media WHERE user_id=?',[$u['id']])->fetchColumn()>500)fail(422,'quota','Quota de photos atteint.');
 $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!isset($allowed[$mime]))fail(422,'mime','Utilisez JPEG, PNG ou WebP.','استخدم JPEG أو PNG أو WebP.');$ext=strtolower(pathinfo($f['name'],PATHINFO_EXTENSION));if(!in_array($ext,['jpg','jpeg','png','webp'],true))fail(422,'extension','Extension non autorisée.');$size=getimagesize($f['tmp_name']);if(!$size||$size[0]*$size[1]>20000000||$size[0]<32||$size[1]<32)fail(422,'dimensions','Dimensions non autorisées.');
 $img=imagecreatefromstring(file_get_contents($f['tmp_name']));if(!$img)fail(422,'decode','Image illisible.');
 if($mime==='image/jpeg'&&function_exists('exif_read_data')){$exif=@exif_read_data($f['tmp_name']);$orientation=$exif['Orientation']??1;if(in_array($orientation,[3,6,8],true)){$angle=[3=>180,6=>-90,8=>90][$orientation];$rot=imagerotate($img,$angle,0);imagedestroy($img);$img=$rot;}}
 $w=imagesx($img);$h=imagesy($img);$ratio=min(1,1600/max($w,$h));$out=imagecreatetruecolor((int)round($w*$ratio),(int)round($h*$ratio));$white=imagecolorallocate($out,255,255,255);imagefill($out,0,0,$white);imagecopyresampled($out,$img,0,0,0,0,imagesx($out),imagesy($out),$w,$h);$name=bin2hex(random_bytes(20)).'.jpg';$dir=UPLOAD_DIR.'/companions';if(!is_dir($dir)&&!mkdir($dir,0770,true))fail(503,'storage','Stockage indisponible.');if(!imagejpeg($out,$dir.'/'.$name,86))fail(503,'storage','Écriture impossible.');imagedestroy($img);imagedestroy($out);$path=UPLOAD_URL_BASE.'/companions/'.$name;q('INSERT INTO uploaded_media(user_id,path,mime,private) VALUES(?,?,"image/jpeg",0)',[$u['id'],$path]);return ['path'=>$path,'media_id'=>(int)db()->lastInsertId()];
}
function movement(): array {$baseline=(int)setting('movement_baseline',100);$n=(int)q('SELECT COUNT(*) FROM registration_events WHERE counted=1')->fetchColumn();$registered=$baseline+$n;return ['baseline'=>$baseline,'registered'=>$registered,'remaining'=>max(0,1000000000-$registered),'target'=>1000000000,'updated_at'=>gmdate('c')];}
