<?php
require_once __DIR__.'/commerce.php';
function nero_knowledge(): array {$entries=[
 'identity'=>['mots'=>['petica','identite','هوية','بطاقة','carte'],'fr'=>'PETICA relie votre compagnon à une identité permanente, une carte et deux destinations QR. Les données publiées peuvent changer sans remplacer les QR.','ar'=>'تربط PETICA رفيقك بهوية دائمة وبطاقة ووجهتي QR. يمكنك تحديث البيانات المنشورة دون تغيير الرموز.','route'=>'comment-ca-marche.html'],
 'lost'=>['mots'=>['perdu','trouve','ضياع','ضائع','ضياع','retrouve'],'fr'=>'Activez le Mode Perdu depuis le dossier de votre compagnon. Le visiteur peut appeler le contact publié et partager sa position avec son accord. Vous seul confirmez le retour.','ar'=>'فعّل وضع الضياع من ملف رفيقك. يمكن للزائر الاتصال بالرقم المنشور ومشاركة موقعه بموافقته. المالك هو من يؤكد العودة.','route'=>'animal-perdu.html'],
 'location'=>['mots'=>['position','gps','localisation','موقع','geolocalisation','refuse'],'fr'=>'La médaille ne contient pas de GPS. La position provient du navigateur du visiteur, uniquement après son accord. Le refus ne bloque pas le contact. Les positions sont privées.','ar'=>'الميدالية لا تحتوي على GPS. الموقع يأتي من متصفح الزائر بموافقته فقط. الرفض لا يمنع الاتصال، والمواقع خاصة.','route'=>'animal-perdu.html'],
 'register'=>['mots'=>['inscri','compte','photo','etape','تسجيل','حساب','صورة'],'fr'=>'L’inscription comprend Compte, Propriétaire, Compagnon, Photo, Résumé, Produit et Confirmation. Votre brouillon se conserve dans votre compte. Aucun OTP obligatoire.','ar'=>'التسجيل يشمل الحساب والمالك والرفيق والصورة والملخص والمنتج والتأكيد. تُحفظ المسودة في حسابك. لا يلزم رمز OTP.','route'=>'inscription/client.html'],
 'secondary'=>['mots'=>['secondaire','titulaire','ثانوي'],'fr'=>'Le propriétaire principal ajoute un nom puis confirme. La carte secondaire bénéficie de 10 % de remise, reprend les contacts principaux et ne crée ni identité ni médaille supplémentaire.','ar'=>'يضيف المالك الرئيسي اسمًا ثم يؤكده. البطاقة الثانوية بتخفيض 10٪ وتستخدم بيانات الاتصال الرئيسية، دون هوية أو ميدالية إضافية.','route'=>'espace-client/compagnons.html'],
 'professional'=>['mots'=>['profession','veterinaire','toiletteur','مهني','بيطري'],'fr'=>'Un compte professionnel doit être vérifié par PETICA. L’accès aux dossiers dépend ensuite de l’accord du client et des droits métier.','ar'=>'يجب أن تتحقق PETICA من الحساب المهني. الوصول للملفات يتطلب موافقة العميل وصلاحيات المهنة.','route'=>'inscription/pro.html'],
 'world'=>['mots'=>['tracker','world','market','breedmatch','clothing','care match','مستقبل'],'fr'=>'Les six projets PETICA World sont en préparation. Tag Tracker est un projet futur : aucune disponibilité ni fonction GPS commercialisée n’est annoncée ici.','ar'=>'مشاريع PETICA World الستة قيد الإعداد. Tag Tracker مشروع مستقبلي؛ لا نعلن عن توفره أو بيع وظيفة GPS.','route'=>'world.html'],
 'movement'=>['mots'=>['billion','milliard','mouvement','مليار'],'fr'=>'Le Mouvement part de la base historique de 100 identités fournie par PETICA. Chaque nouvelle identité éligible décrémente le restant une seule fois. Les démonstrations ne comptent pas.','ar'=>'تبدأ الحركة من الرصيد التاريخي البالغ 100 هوية الذي قدمته PETICA. كل هوية جديدة مؤهلة تخفض العدد المتبقي مرة واحدة. العروض التجريبية لا تُحتسب.','route'=>'billion-movement.html'],
 'notifications'=>['mots'=>['notif','alerte','اشعار','إشعار','تنبيه'],'fr'=>'Une consultation QR signalée crée un événement persistant. Les alertes apparaissent dans votre espace. Email, push ou SMS ne fonctionnent que si leur transport est configuré et testé.','ar'=>'فتح QR المسجّل ينشئ حدثًا محفوظًا. تظهر التنبيهات في مساحتك. البريد والإشعارات والرسائل تعمل فقط عند إعداد واختبار الخدمة.','route'=>'espace-client/notifications.html'],
 'reset'=>['mots'=>['passe','password','oubli','مرور'],'fr'=>'Utilisez « Mot de passe oublié ». Un lien à usage unique nécessite un service email configuré. Si ce service est indisponible, contactez PETICA.','ar'=>'استخدم «نسيت كلمة المرور». رابط الاستخدام الواحد يتطلب خدمة بريد مهيأة. إن كانت غير متاحة فتواصل مع PETICA.','route'=>'auth/mot-de-passe-oublie.html'],
 'contact'=>['mots'=>['contact','telephone','whatsapp','هاتف','تواصل'],'fr'=>'PETICA : +216 24 300 864. WhatsApp : +216 56 224 498. Je peux vous orienter ; je n’envoie pas de message à votre place.','ar'=>'PETICA: +216 24 300 864. واتساب: +216 56 224 498. يمكنني إرشادك، ولا أرسل الرسائل نيابة عنك.','route'=>'contact.html'],
 ];foreach($entries as $k=>&$entry){$v=one('SELECT body_fr,body_ar FROM content_versions WHERE slug=? AND status="published" ORDER BY id DESC LIMIT 1',['nero/'.$k]);if($v){$entry['fr']=$v['body_fr'];$entry['ar']=$v['body_ar'];}}unset($entry);return $entries;}
function nero_ask(array $b,?array $u): array {$message=mb_strtolower(text_field($b,'message',2000,true));$m=strtr($message,['é'=>'e','è'=>'e','ê'=>'e','à'=>'a','ô'=>'o','أ'=>'ا','إ'=>'ا','آ'=>'ا']);$m=preg_replace('/[\x{064B}-\x{065F}\x{0640}]/u','',$m);if(preg_match('/prix|tarif|combo|promo|livraison|remise|سعر|تخفيض|توصيل|اسعار/u',$m)){if(str_contains($m,'tracker'))$key='world';else{$products=q('SELECT name_fr,name_ar,price_tnd FROM products WHERE active=1 AND commercial_approved=1 ORDER BY id')->fetchAll();$lines=array_map(fn($p)=>$p['name_'.lang()].' : '.money((int)round((float)$p['price_tnd']*1000)),$products);return ['answer'=>implode(' · ',$lines).tr('. Livraison : 8 TND. Le configurateur vérifie les remises et les codes. Un Combo non approuvé reste indisponible.','. التوصيل: 8 TND. حاسبة السعر تتحقق من التخفيضات والرموز. الباقة غير المعتمدة تبقى غير متاحة.'),'source'=>'catalogue','action'=>'tarifs.html'];}}
 if(!isset($key)){$score=0;$key=null;foreach(nero_knowledge() as $k=>$entry){$n=0;foreach($entry['mots'] as $word)if(str_contains($m,$word))$n+=mb_strlen($word);if($n>$score){$score=$n;$key=$k;}}}if(!$key)return ['answer'=>tr('Je n’ai pas de réponse vérifiée à cette question. Précisez votre demande ou contactez PETICA.','لا أملك إجابة موثوقة لهذا السؤال. وضّح طلبك أو تواصل مع PETICA.'),'source'=>'limite','action'=>'contact.html'];$r=nero_knowledge()[$key];return ['answer'=>$r[lang()],'source'=>'PETICA · '.$key,'action'=>$r['route']];}
