<?php
require_once __DIR__.'/recovery.php';
function qr_page(string $kind,string $value='',?int $legacyId=null): void {
 headers_safe();start();$error=null;$c=null;$nonce=null;
 try{
  if(strlen($value)>100)fail(404,'qr','QR introuvable.');
  if($legacyId!==null){$c=one('SELECT * FROM companions WHERE id=? AND serial_number=?',[$legacyId,$value]);if(!$c)$c=one('SELECT c.* FROM serial_aliases a JOIN companions c ON c.id=a.companion_id WHERE a.alias=? AND c.id=?',[$value,$legacyId]);}
  elseif($kind==='tag'){$r=qr_resolve_token($value);if($r&&$r['kind']==='tag')$c=$r['companion'];}
  else{$r=qr_resolve_token($value);if($r&&$r['kind']==='identity')$c=$r['companion'];if(!$c)$c=one('SELECT * FROM companions WHERE serial_number=?',[$value]);if(!$c)$c=one('SELECT c.* FROM serial_aliases a JOIN companions c ON c.id=a.companion_id WHERE a.alias=?',[$value]);}
  if(!$c)fail(404,'qr','Cette identité est introuvable. Vérifiez le QR.','لم يتم العثور على الهوية. تحقق من QR.');
  if(one('SELECT u.id FROM users u JOIN companion_owners co ON co.user_id=u.id WHERE co.companion_id=? AND u.is_demo=1',[$c['id']])&&!cfg('ALLOW_DEMO',false))fail(404,'qr','Identité indisponible.');
  $v=companion_public_view($c,$kind);$name=$v['name'];
  if($kind==='tag'&&$c['status']!=='deceased'){$nonce=scan_nonce((int)$c['id']);if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check($_POST);$r=scan_create($_POST);$_SESSION['qr_report_message']=tr('Votre consultation est enregistrée. Vous pouvez contacter le propriétaire.','تم تسجيل الزيارة. يمكنك التواصل مع المالك.');header('Location: '.($_SERVER['REQUEST_URI']),true,303);exit;}}
 }catch(ApiError $e){http_response_code($e->status);$error=$e->getMessage();}catch(Throwable $e){http_response_code(503);$error=tr('Le profil est momentanément indisponible. Réessayez.','الملف غير متاح مؤقتًا. أعد المحاولة.');error_log('PETICA public QR '.get_class($e));}
 $scriptNonce=base64_encode(random_bytes(18));header("Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-$scriptNonce'; style-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'");
 $params=$_GET;$params['lang']=lang()==='fr'?'ar':'fr';$switch=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH).'?'.http_build_query($params);
 ?><!doctype html><html lang="<?=lang()?>" dir="<?=lang()==='ar'?'rtl':'ltr'?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow"><title><?=esc($error?'PETICA':$name.' · PETICA')?></title><link rel="stylesheet" href="<?=esc(url('css/universe.css'))?>"><meta name="csrf-token" content="<?=esc(csrf())?>"><meta name="app-base" content="<?=esc(APP_BASE)?>"><script src="<?=esc(url('js/qr-recovery.js'))?>" defer></script></head><body class="qr-page"><header class="qr-header"><a href="<?=esc(url(lang().'/index.html'))?>"><img src="<?=esc(url('assets/icons/logo-full-purple.svg'))?>" width="126" height="42" alt="PETICA"></a><a href="<?=esc($switch)?>"><?=lang()==='fr'?'العربية':'FR'?></a></header><main class="qr-main">
 <?php if($error): ?><h1><?=esc($error)?></h1><a class="button secondary" href="tel:+21624300864"><?=esc(tr('Contacter PETICA','الاتصال بـ PETICA'))?></a><?php else: ?>
 <p class="eyebrow"><?=esc($kind==='tag'?tr('PETICA · Récupération','PETICA · العودة'):tr('PETICA · Identité permanente','PETICA · هوية دائمة'))?></p><h1><?=esc($name)?></h1><p class="status status-<?=esc($v['status'])?>"><?=esc(['present'=>tr('Ce compagnon a une identité PETICA.','لهذا الرفيق هوية PETICA.'),'lost'=>tr('Compagnon déclaré perdu','تم الإبلاغ عن ضياع الرفيق'),'deceased'=>tr('En mémoire de ce compagnon','في ذكرى هذا الرفيق')][$v['status']]??$v['status'])?></p><bdi class="serial"><?=esc($v['serial_number'])?></bdi>
 <?php if($v['lost_message']): ?><p class="lost-message"><?=esc($v['lost_message'])?></p><?php endif;if($v['contact_phone']&&$c['status']!=='deceased'): ?><a class="button emergency" href="tel:<?=esc(preg_replace('/[^+0-9]/','',$v['contact_phone']))?>"><?=esc(tr('Appeler le contact','اتصل بجهة الاتصال'))?></a><p><?=esc($v['contact_name'])?> · <bdi><?=esc($v['contact_phone'])?></bdi></p><?php elseif($c['status']!=='deceased'): ?><p><?=esc(tr('Aucun téléphone n’a été autorisé à la publication.','لم يُسمح بنشر رقم هاتف.'))?></p><a class="button secondary" href="tel:+21624300864"><?=esc(tr('Contacter PETICA','الاتصال بـ PETICA'))?></a><?php endif ?>
 <?php if($v['photo_url']&&str_starts_with($v['photo_url'],APP_BASE.'/')): ?><img class="qr-portrait" src="<?=esc($v['photo_url'])?>" width="320" height="320" alt="<?=esc($name)?>" loading="lazy"><?php endif ?><p><?=esc($v['breed'])?> <?=esc($v['colors_marks'])?></p>
 <?php if($nonce): ?><section id="scan-recovery" data-nonce="<?=esc($nonce)?>"><h2><?=esc(tr('Aider à reprendre contact','المساعدة على استعادة التواصل'))?></h2><p><?=esc(tr('Cette consultation peut être signalée au propriétaire. Le lien ouvert ne prouve pas, à lui seul, qu’un animal a été vu.','يمكن إبلاغ المالك بهذه الزيارة. فتح الرابط وحده لا يثبت رؤية الرفيق.'))?></p><p id="scan-status" role="status"><?=esc($_SESSION['qr_report_message']??tr('Votre contact reste possible sans partager de position.','يمكنك التواصل دون مشاركة الموقع.'))?></p><?php unset($_SESSION['qr_report_message']); ?><button class="button secondary" id="share-location" type="button" hidden><?=esc(tr('Partager ma position avec le propriétaire','مشاركة موقعي مع المالك'))?></button><p class="muted"><?=esc(tr('Avec votre accord, le navigateur transmet une position ponctuelle et sa précision. Elle est privée et conservée 30 jours par défaut. La médaille ne contient pas de GPS.','بموافقتك يرسل المتصفح موقعًا واحدًا ودقته. الموقع خاص ويُحفظ 30 يومًا افتراضيًا. الميدالية لا تحتوي على GPS.'))?></p><p id="location-status" role="status"></p><noscript><form method="post"><input type="hidden" name="_csrf" value="<?=esc(csrf())?>"><input type="hidden" name="nonce" value="<?=esc($nonce)?>"><input type="hidden" name="lang" value="<?=lang()?>"><button class="button secondary"><?=esc(tr('Signaler cette consultation','الإبلاغ عن هذه الزيارة'))?></button></form></noscript></section><?php endif;endif ?>
 </main><footer class="qr-footer"><a href="<?=esc(url(lang().'/confidentialite.html'))?>"><?=esc(tr('Confidentialité','الخصوصية'))?></a><a href="<?=esc(url(lang().'/compte-type.html'))?>"><?=esc(tr('Inscrire votre compagnon','سجّل رفيقك'))?></a></footer></body></html><?php
}
