<?php
require_once __DIR__.'/identity.php';
function lost_change(int $id,array $b,array $u): array {
 allow_companion($id,$u,'identity',true);$status=enum_field($b,'status',['present','lost','deceased']);if(!$status)fail(422,'status','État requis.');$reason=text_field($b,'reason',1000);$message=text_field($b,'lost_message',1500);
 return tx(function()use($id,$b,$u,$status,$reason,$message){$c=one('SELECT * FROM companions WHERE id=? FOR UPDATE',[$id]);if((int)($b['version']??0)!==(int)$c['version'])fail(409,'version','Le statut a changé. Rechargez le dossier.','تغيرت الحالة. أعد تحميل الملف.');if($c['status']===$status)return ['companion'=>$c];if($c['status']==='deceased')fail(409,'transition','Ce statut nécessite une correction administrative documentée.');
 $open=one('SELECT * FROM lost_cases WHERE companion_id=? AND state="open" FOR UPDATE',[$id]);if($status==='lost'&&!$open){q('INSERT INTO lost_cases(companion_id,state,activated_by,reason) VALUES(?,"open",?,?)',[$id,$u['id'],$reason]);}elseif($open&&$status!=='lost'){q('UPDATE lost_cases SET state="resolved",resolved_by=?,resolved_at=UTC_TIMESTAMP(),reason=? WHERE id=?',[$u['id'],$reason,$open['id']]);}
 q('UPDATE companions SET status=?,lost_message=?,lost_since=IF(?="lost",UTC_TIMESTAMP(),NULL),version=version+1 WHERE id=?',[$status,$status==='lost'?$message:null,$status,$id]);audit('companion.status','companion',$id,['before'=>$c['status'],'after'=>$status,'reason'=>$reason]);return ['companion'=>companion($id)];});
}
function scan_nonce(int $id): string {start();foreach($_SESSION['scan_nonces']??[] as $k=>$v)if($v['expires']<time())unset($_SESSION['scan_nonces'][$k]);$n=bin2hex(random_bytes(24));$_SESSION['scan_nonces'][$n]=['companion_id'=>$id,'expires'=>time()+300];return $n;}
function scan_create(array $b): array {
 rate('scan',20,60);start();$nonce=(string)($b['nonce']??'');$grant=$_SESSION['scan_nonces'][$nonce]??null;if(!$grant||$grant['expires']<time())fail(403,'scan_nonce','Rechargez la page du QR pour signaler cette consultation.','أعد تحميل صفحة QR لتسجيل الزيارة.');$cid=(int)$grant['companion_id'];$visitor=hash('sha256',session_id());
 return tx(function()use($nonce,$cid,$visitor){$c=one('SELECT id,status FROM companions WHERE id=? FOR UPDATE',[$cid]);if(!$c)fail(404,'qr','Identité introuvable.');if($c['status']==='deceased')fail(409,'inactive','La récupération est inactive pour cette identité.');
 $prior=one('SELECT * FROM qr_scan_events WHERE companion_id=? AND visitor_hash=? AND (received_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 120 SECOND) OR nonce_hash=?) ORDER BY id DESC LIMIT 1',[$cid,$visitor,hash('sha256',$nonce)]);
 if($prior&&isset($_SESSION['scan_capabilities'][$prior['public_id']]))return ['event'=>$prior['public_id'],'capability'=>$_SESSION['scan_capabilities'][$prior['public_id']],'location_status'=>$prior['location_status'],'duplicate'=>true];
 $case=one('SELECT id FROM lost_cases WHERE companion_id=? AND state="open"',[$cid]);$event=bin2hex(random_bytes(24));$cap=bin2hex(random_bytes(32));q('INSERT INTO qr_scan_events(public_id,companion_id,lost_case_id,nonce_hash,visitor_hash,capability_hash,capability_expires) VALUES(?,?,?,?,?,?,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 15 MINUTE))',[$event,$cid,$case['id']??null,hash('sha256',$nonce),$visitor,hash('sha256',$cap)]);$eid=(int)db()->lastInsertId();q('INSERT INTO qr_scan_event_entries(event_id,type) VALUES(?,"page_reported")',[$eid]);
 $owners=q('SELECT co.user_id FROM companion_owners co JOIN users u ON u.id=co.user_id WHERE co.companion_id=? AND co.relationship="primary" AND u.status="active" AND u.is_demo=0',[$cid])->fetchAll();foreach($owners as $o){$recent=(int)q('SELECT COUNT(*) FROM notifications n JOIN qr_scan_events e ON e.id=n.related_id WHERE n.user_id=? AND n.related_type="scan" AND e.companion_id=? AND n.created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 MINUTE)',[$o['user_id'],$cid])->fetchColumn();if($recent<5)notify((int)$o['user_id'],'qr_scan','Votre compagnon vient d’être scanné.','تم فتح صفحة QR لرفيقك.','scan',$eid);}
 $_SESSION['scan_capabilities'][$event]=$cap;return ['event'=>$event,'capability'=>$cap,'location_status'=>'not_requested','duplicate'=>false];});
}
function encryption_key(): string {$key=base64_decode((string)cfg('APP_KEY',''),true);if($key===false||strlen($key)!==32)fail(503,'location_not_configured','Le partage de position est indisponible. Vous pouvez toujours appeler.','مشاركة الموقع غير متاحة. يمكنك الاتصال.');return $key;}
function scan_location(string $event,array $b): array {
 $r=one('SELECT * FROM qr_scan_events WHERE public_id=?',[$event]);$cap=(string)($b['capability']??'');if(!$r||!hash_equals($r['capability_hash'],hash('sha256',$cap)))fail(403,'capability','Action non autorisée.','العملية غير مسموحة.');if(strtotime($r['capability_expires'].' UTC')<time())fail(410,'expired','Délai de partage expiré. Rechargez le QR.','انتهت مهلة المشاركة. أعد فتح QR.');
 $state=enum_field($b,'status',['available','denied','unsupported','insecure','timeout','unavailable']);if(!$state)fail(422,'location_status','État requis.');$cipher=null;
 if($state==='available'){if(($b['consent']??'')!=='location-v1')fail(422,'consent','Consentement requis.');$lat=$b['latitude']??null;$lon=$b['longitude']??null;$accuracy=$b['accuracy']??null;foreach([$lat,$lon,$accuracy] as $v)if(!is_numeric($v)||!is_finite((float)$v))fail(422,'coordinates','Coordonnées invalides.');if(abs((float)$lat)>90||abs((float)$lon)>180||(float)$accuracy<0||(float)$accuracy>100000)fail(422,'coordinates','Coordonnées hors limites.');$at=(float)($b['captured_at']??0);if(abs(time()-$at/1000)>300)fail(422,'capture_time','Position trop ancienne. Réessayez.');$payload=json_encode(['latitude'=>(float)$lat,'longitude'=>(float)$lon,'accuracy'=>(float)$accuracy,'captured_at'=>gmdate('c',(int)($at/1000))]);$iv=random_bytes(12);$tag='';$bytes=openssl_encrypt($payload,'aes-256-gcm',encryption_key(),OPENSSL_RAW_DATA,$iv,$tag,$event);if($bytes===false)fail(503,'encryption','Partage indisponible.');$cipher=base64_encode($iv.$tag.$bytes);}
 return tx(function()use($r,$event,$state,$cipher){$locked=one('SELECT * FROM qr_scan_events WHERE id=? FOR UPDATE',[$r['id']]);if(strtotime($locked['capability_expires'].' UTC')<time())fail(410,'expired','Délai de partage expiré.');if($locked['location_status']==='available')return ['event'=>$event,'location_status'=>'available'];$days=max(1,min(90,(int)cfg('LOCATION_DAYS',30)));q('UPDATE qr_scan_events SET location_status=?,location_cipher=?,consent_version=?,consent_at=IF(?="available",UTC_TIMESTAMP(),NULL),location_expires=IF(?="available",DATE_ADD(UTC_TIMESTAMP(),INTERVAL '.$days.' DAY),NULL) WHERE id=?',[$state,$cipher,$state==='available'?'location-v1':null,$state,$state,$r['id']]);q('INSERT IGNORE INTO qr_scan_event_entries(event_id,type) VALUES(?,?)',[$r['id'],'location_'.$state]);return ['event'=>$event,'location_status'=>$state];});
}
function scan_detail(string $event,array $u): array {$r=one('SELECT * FROM qr_scan_events WHERE public_id=?',[$event]);if(!$r)fail(404,'event','Événement introuvable.');allow_companion((int)$r['companion_id'],$u,'recovery');$position=null;$expired=$r['location_expires']&&strtotime($r['location_expires'].' UTC')<time();if($r['location_cipher']&&!$expired){$bytes=base64_decode($r['location_cipher'],true);$plain=openssl_decrypt(substr($bytes,28),'aes-256-gcm',encryption_key(),OPENSSL_RAW_DATA,substr($bytes,0,12),substr($bytes,12,16),$r['public_id']);if($plain!==false)$position=json_decode($plain,true);}
 return ['event'=>['public_id'=>$r['public_id'],'received_at'=>$r['received_at'],'location_status'=>$expired?'expired':$r['location_status'],'companion_id'=>(int)$r['companion_id'],'position'=>$position],'timeline'=>q('SELECT type,server_at FROM qr_scan_event_entries WHERE event_id=? ORDER BY server_at,id',[$r['id']])->fetchAll()];}
function scans_list(int $cid,array $u): array {allow_companion($cid,$u,'recovery');return listing('public_id,received_at,IF(location_expires<UTC_TIMESTAMP(),"expired",location_status) location_status','FROM qr_scan_events WHERE companion_id=?',[$cid],'id DESC');}
